from __future__ import annotations

import json
from pathlib import Path

from fos_api.main import app

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "packages" / "contracts" / "dist" / "api"
OPENAPI_PATH = OUT_DIR / "openapi.json"
CLIENT_PATH = OUT_DIR / "client.ts"
CLIENT_JS_PATH = OUT_DIR / "client.js"
CLIENT_DTS_PATH = OUT_DIR / "client.d.ts"


def _function_name(method: str, path: str) -> str:
    parts = [method.lower()]
    for part in path.strip("/").replace("{", "by_").replace("}", "").replace("-", "_").split("/"):
        if not part:
            continue
        parts.extend(piece for piece in part.split("_") if piece)
    return parts[0] + "".join(piece[:1].upper() + piece[1:] for piece in parts[1:])


def _client_source(schema: dict[str, object]) -> str:
    paths = schema.get("paths", {})
    if not isinstance(paths, dict):
        paths = {}
    functions: list[str] = []
    for path in sorted(paths):
        methods = paths[path]
        if not isinstance(methods, dict):
            continue
        for method in sorted(methods):
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            name = _function_name(method, path)
            template = path.replace("{", "${encodeURIComponent(String(params.").replace("}", "))}")
            signature = (
                f"export async function {name}(params: Record<string, unknown> = {{}}, "
                "body?: unknown): Promise<unknown> {"
            )
            body_arg = "body" if method in {"post", "put", "patch"} else "undefined"
            functions.append(
                "\n".join(
                    [
                        signature,
                        f"  return request(`{template}`, {{ method: \"{method.upper()}\", body: {body_arg} }});",
                        "}",
                    ]
                )
            )
    return "\n\n".join(
        [
            "/* Auto-generated by tools/codegen/openapi_to_ts.py. Do not edit by hand. */",
            "export const API_CLIENT_VERSION = \"0.1.0\";",
            "export const API_BASE_URL = process.env.FOS_API_BASE_URL ?? \"http://localhost:8000\";",
            "",
            "type RequestOptions = { method: string; body?: unknown };",
            "",
            "async function request(path: string, options: RequestOptions): Promise<unknown> {",
            "  const response = await fetch(`${API_BASE_URL}${path}`, {",
            "    method: options.method,",
            "    headers: options.body === undefined ? undefined : { \"content-type\": \"application/json\" },",
            "    body: options.body === undefined ? undefined : JSON.stringify(options.body),",
            "  });",
            "  if (!response.ok) {",
            "    throw new Error(`FOS API ${options.method} ${path} failed: ${response.status}`);",
            "  }",
            "  const contentType = response.headers.get(\"content-type\") ?? \"\";",
            "  return contentType.includes(\"application/json\") ? response.json() : response.blob();",
            "}",
            "",
            *functions,
            "",
        ]
    )


def _client_declarations(schema: dict[str, object]) -> str:
    paths = schema.get("paths", {})
    if not isinstance(paths, dict):
        paths = {}
    declarations = [
        "/* Auto-generated by tools/codegen/openapi_to_ts.py. Do not edit by hand. */",
        "export declare const API_CLIENT_VERSION = \"0.1.0\";",
        "export declare const API_BASE_URL: string;",
    ]
    for path in sorted(paths):
        methods = paths[path]
        if not isinstance(methods, dict):
            continue
        for method in sorted(methods):
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            name = _function_name(method, path)
            declarations.append(
                f"export declare function {name}(params?: Record<string, unknown>, body?: unknown): Promise<unknown>;"
            )
    return "\n".join(declarations) + "\n"


def _js_source(ts_source: str) -> str:
    source = ts_source.replace("type RequestOptions = { method: string; body?: unknown };\n\n", "")
    source = source.replace(": Promise<unknown>", "")
    source = source.replace(": RequestOptions", "")
    source = source.replace("body?: unknown", "body")
    source = source.replace(": string", "")
    source = source.replace(": unknown", "")
    source = source.replace("params: Record<string, unknown> = {}", "params = {}")
    return source


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    schema = app.openapi()
    OPENAPI_PATH.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    ts_source = _client_source(schema)
    CLIENT_PATH.write_text(ts_source.rstrip() + "\n", encoding="utf-8")
    CLIENT_JS_PATH.write_text(_js_source(ts_source).rstrip() + "\n", encoding="utf-8")
    CLIENT_DTS_PATH.write_text(_client_declarations(schema), encoding="utf-8")


if __name__ == "__main__":
    main()
